"""Alert policy schemas."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AlertLevel(str, Enum):
    LOW_RISK = "low_risk"
    MEDIUM_RISK = "medium_risk"
    HIGH_RISK = "high_risk"
    INCONCLUSIVE = "inconclusive"


class AlertAction(str, Enum):
    # Low risk
    CONTINUE_MONITORING = "continue_monitoring"
    STORE_AGGREGATE_TELEMETRY = "store_aggregate_telemetry"

    # Medium risk
    WARN_ANALYST = "warn_analyst"
    INCREASE_SAMPLING = "increase_sampling"
    REQUEST_VERIFICATION = "request_verification"
    STEP_UP_AUTHENTICATION = "step_up_authentication"

    # High risk
    NOTIFY_INVESTIGATORS = "notify_investigators"
    FREEZE_ANALYSIS_WINDOW = "freeze_analysis_window"
    CAPTURE_MINIMUM_EVIDENCE = "capture_minimum_evidence"
    GENERATE_EVIDENCE_PACKAGE = "generate_evidence_package"
    LOG_POLICY_DECISION = "log_policy_decision"

    # Inconclusive
    REQUEST_BETTER_CAPTURE = "request_better_capture"
    ESCALATE_TO_MANUAL_REVIEW = "escalate_to_manual_review"


class AlertPolicy(BaseModel):
    """Configurable thresholds for alert routing."""
    policy_version: str = "1.0"
    high_risk_threshold: float = 0.80
    medium_risk_threshold: float = 0.50
    low_risk_threshold: float = 0.20
    min_confidence_for_decision: float = 0.40
    throttle_window_seconds: int = 30
    max_alerts_per_window: int = 3
    require_human_review_above: float = 0.50
    evidence_capture_requires_policy_approval: bool = True


class AlertEvent(BaseModel):
    """A single alert produced by the alert policy engine."""
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    analysis_id: str
    event_id: str
    case_id: str | None = None

    level: AlertLevel
    actions: list[AlertAction] = Field(default_factory=list)

    synthetic_media_probability: float | None = None
    confidence: float | None = None
    top_signals: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)

    # Policy decision trace
    policy_version: str | None = None
    policy_decision_rationale: str | None = None

    # Temporal smoothing metadata (for live streams)
    is_smoothed: bool = False
    smoothing_window_s: float | None = None

    triggered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)

    disclaimer: str = (
        "This alert is generated by automated software and does NOT constitute "
        "a legal accusation or identity determination. Alerts above medium risk "
        "require human analyst review before any investigative action."
    )

    model_config = {"use_enum_values": True}
